"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os

import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Di Railway, set SECRET_KEY lewat Environment Variables. Nilai default di bawah
# hanya dipakai saat development lokal (tidak ada env var SECRET_KEY).
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-y12jun3#4gj$gbc4al_t$l)5u^1m8oxl@2ei9b_o-)1d-iog8)'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('ALLOWED_HOSTS', '*').split(',') if h.strip()
]

# Railway men-terminate HTTPS di reverse proxy-nya, jadi Django perlu tahu
# origin HTTPS mana yang dipercaya untuk validasi CSRF pada form POST.
CSRF_TRUSTED_ORIGINS = [
    f'https://{h}' for h in ALLOWED_HOSTS if h and h != '*'
]

# Supaya Django tahu request aslinya HTTPS (bukan HTTP) walau diteruskan
# lewat proxy Railway, sehingga cookie secure & redirect berjalan benar.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lms',
    'silk',

    'ninja_simple_jwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'lms.middleware.DualCookieSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'lms.middleware.NoCacheForAuthenticatedMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    # Profiling Django Silk hanya aktif saat development.
    MIDDLEWARE.append('silk.middleware.SilkyMiddleware')

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Railway otomatis menyediakan DATABASE_URL saat PostgreSQL service ditambahkan.
# Tanpa DATABASE_URL (misal saat development lokal), tetap fallback ke SQLite.

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ['DATABASE_URL'],
            conn_max_age=600,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Auth
# Halaman dashboard/admin redirect ke sini kalau belum login (@login_required)
LOGIN_URL = '/login/'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (upload gambar course, PDF materi, dll)
# Catatan: agar file upload tetap ada setelah redeploy, attach Railway Volume
# yang di-mount ke path MEDIA_ROOT ini.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email (untuk fitur lupa password). Default: console backend (email hanya
# dicetak ke log container, cukup untuk development). Untuk production di
# Railway, set EMAIL_BACKEND ke 'django.core.mail.backends.smtp.EmailBackend'
# lewat Environment Variables beserta EMAIL_HOST/EMAIL_HOST_USER/dst supaya
# email reset password benar-benar terkirim.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@sagaracourse.com')

# Google OAuth2 (tombol "Login/Register dengan Google"). Buat kredensial di
# Google Cloud Console > APIs & Services > Credentials > OAuth client ID,
# lalu isi env var GOOGLE_CLIENT_ID & GOOGLE_CLIENT_SECRET. Kalau kosong,
# tombol Google akan menampilkan pesan error alih-alih redirect ke Google.
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')

# JWT signing key (django-ninja-simple-jwt).
# Di Railway, file jwt-signing.pem/.pub tidak ikut deploy (gitignored), jadi key
# diambil dari env var JWT_PRIVATE_KEY/JWT_PUBLIC_KEY. Kalau env var tidak diset
# (misal saat development lokal), library fallback baca file jwt-signing.pem/.pub.
NINJA_SIMPLE_JWT = {
    "JWT_PRIVATE_KEY": os.environ.get("JWT_PRIVATE_KEY"),
    "JWT_PUBLIC_KEY": os.environ.get("JWT_PUBLIC_KEY"),
}