# Generated by Django 5.2.13 on 2026-04-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='contents', to='lms.course', verbose_name='matkul'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='lms.coursecontent', verbose_name='induk'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='materi/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Video'),
        ),
    ]
