# Generated by Django 5.2.13 on 2026-06-24 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_course_max_students_alter_comment_content_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='judul topik'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lms.coursecontent', verbose_name='konten'),
        ),
    ]
