# Generated by Django 5.2.13 on 2026-06-25 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_comment_title_alter_comment_content_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lms.course', verbose_name='matkul (ulasan)'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('development', 'Development'), ('business', 'Business'), ('marketing', 'Marketing'), ('data_science', 'Data Science'), ('photography', 'Photography')], default='development', max_length=20, verbose_name='kategori'),
        ),
        migrations.CreateModel(
            name='ContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='lms.coursecontent', verbose_name='konten')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lms.coursemember', verbose_name='siswa')),
            ],
            options={
                'verbose_name': 'Progress Materi',
                'verbose_name_plural': 'Progress Materi',
                'unique_together': {('member', 'content')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lms.coursecontent', verbose_name='konten')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lms.coursemember', verbose_name='siswa')),
            ],
            options={
                'verbose_name': 'Catatan Pribadi',
                'verbose_name_plural': 'Catatan Pribadi',
                'unique_together': {('member', 'content')},
            },
        ),
    ]
