# Generated by Django 5.2.13 on 2026-06-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_coursemember_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video Lokal'),
        ),
    ]
